### ISSUE TITLE
Price variable missing from shipping

### ISSUE THREAD

**Issue by davidvk89** [hy-company/peer2product#6]
When writing a transport rule the $result variable does not hold price data(as the documentation suggests). This makes it impossible to add free shipping based on total price.

Added a custom fix to kunsthuis that sets the jcart->subtotal variable to public and then puts it in a session to use in the transport formula. This is a security issue however and needs a better fix for the peer2product launch.

**Comment by agent725** [comment]
Fixes have been applied. We should check if everything works and then we can close this issue.

**Comment by davidvk89** [comment]
Has this fix been checked with the wageningen pilot store? If so this issue can be closed.
